### PR TITLE
[REF] use a config object (extendable)

### PR DESCRIPTION
**Pull request by blaggacao**
Refactor towards a config object and pass positional and named argument in order to be able to selectively extend the command line options in downstream `click-odoo` scripts.

### CODE REVIEW

**Comment by blaggacao** [comment]
If you agree, I'd prefer moving such into `config.py` (for better transparency)...

**Comment by sbidoul** [comment]
I don't see the goal of this PR. This is an internal implementation detail of click-odoo.

**Comment by blaggacao** [comment]
The idea is more or less to do this: https://github.com/xoe-labs/click-odoo-tester/blob/94197816affa145eff3856d278f1b156a0333c9b/src/tester.py#L108-L122 (but differently)

**Comment by blaggacao** [comment]
@sbidoul I think this is reaching something discussable, please note the second commit is just optional, but I thought a little more separation of concern wouldn't hurt.

**Comment by sbidoul** [comment]
Sorry, I still don't understand the goal of this PR. This does not modify the public API of click-odoo, so why changing this?

**Comment by blaggacao** [comment]
The core goal is separate `parse` (or `seed`) and `_parse` and pass `*args` and `**kwargs` to the parsing function.

This enables lean config pre-processing where needed. If you would prefer changing the public API that would be probably even cleaner. I'll prepare another commit with such implemented.

How I implemented, ultimately, it is just a matter of taste.

**Comment by blaggacao** [comment]
You mean you want to avoid exposing yet another hook? Is that why you tend to be against this PR?

**Comment by blaggacao** [comment]
Your suggestion could be done. Though, I honestly feel it would be a less clean overall code base. Don't you think?

**Comment by sbidoul** [comment]
Yes, as I said. This PR does not allow you to do anything that you cannot do in a reasonably simple other way.

**Comment by blaggacao** [comment]
You might be right with that, however I feel this code is a little cleaner (or is that too opinionated?), and while it can adopted in a way not being exposed on the public API would be "a cleaner code base" too little of an argument?

**Comment by sbidoul** [comment]
I'll close for now, I think your use cases are rather exotic, so they don't warrant a dedicated API.

You have a solution with the environment_manager. Or you could just use a plain old Odoo configuration file and wait until Odoo eventually reworks it's configuration API...

**Comment by blaggacao** [comment]
@sbidoul Trying to implement your suggestion, I find: it is not possible to read the script's command line flags from the `environment_manager`, so I'm not sure weather to "fix" the environment manager (passing `*args` & `**kwargs`) or to continue on this...

**Pull request closed without merging**
