### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by blaggacao**
#### All xoe-labs downstream modules migrated and passing tests.

- Replaces https://github.com/acsone/click-odoo/pull/15
- For motivation and discussion, please refer / stick to #15
- If you want to use this versions:

```python
# setup.py
    ...
    setup_requires=["setuptools-scm"],
    install_requires=["click-odoo>=2.0.0.rc2"],
    dependency_links=[
      'git+https://github.com/xoe-labs/click-odoo.git@2.0.0#egg=click-odoo',
    ],
    license="LGPLv3+",
    ...
```

```ini
# tox.ini

[testenv]
...
deps =
  -rrequirements.txt
  git+https://github.com/xoe-labs/click-odoo.git@2.0.0#egg=click-odoo
  configparser>=3.5.0
  psycopg2
  pytest
  pytest-cov
  pytest-mock
...
[testenv:pre_commit]
deps =
  pre-commit
  git+https://github.com/xoe-labs/click-odoo.git@2.0.0#egg=click-odoo
commands =
  pre-commit run --all-files
```

### CODE REVIEW

**Comment by blaggacao** [comment]
In case you want to migrate, here is an example diff:
```diff
 src/initializer.py | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/src/initializer.py b/src/initializer.py
index 5f1da58..8899226 100644
--- a/src/initializer.py
+++ b/src/initializer.py
@@ -338,10 +338,10 @@ class DbCache:
                 self._drop_db(datname)
 
 
-@click.command()
-@click_odoo.env_options(
-    default_log_level="warn", with_database=False, with_rollback=False
-)
+@click.command(cls=click_odoo.CommandWithOdooEnv, env_options={
+    "with_database": False,
+    "with_rollback": False
+    }, default_overrides={"log_level": "warn"})
 @click.option(
     "--new-database",
     "-n",
```

**Comment by sbidoul** [comment]
As discussed, such a back-ward incompatible change is not necessary.

Have a look at #18, which fixes #16, and is fully backward compatible while being easier to extend.

**Comment by sbidoul** [comment]
> I already don't want to miss the default_overrides key.

What do you mean?

> Wouldn't there be a way to use this 2.0.0 and make a backwards compatible patch

It is possible, but that would double the API surface, hence double the doc and tests. I don't want that unless maybe there are important use cases that the current API does not cover.

> tester screenshot

Looks nice. Is this a log parser? If yes there is no need to make it depend on click-odoo. A standalone tool into which you could pipe an Odoo log from any source would be much more useful versatile.

**Comment by blaggacao** [comment]
> Looks nice. Is this a log parser? If yes there is no need to make it depend on click-odoo. A standalone tool into which you could pipe an Odoo log from any source would be much more useful versatile.

It queries the db-written logs, easy peasy short cut.

default_overridses: easiest check out the change set to the readme of this 2.0.0

Let me check if I can come up with some backport in order not to risk a fork at this point. Test wise, I can tell, it's not a real problem, and the (implicit) aim would be to fade out the old API in the course of 2019.

Under the hood your refactoring uses (almost) the same design, so I see there is only little difference to take into account.

**Comment by sbidoul** [comment]
> Let me check if I can come up with some backport

Don't waste your time: if there is no compelling use case I will not accept it, because, again, I don't want to double the API surface, and I see no reason to fade out the current API if it has no shortcoming.

> default_overrides

It adds the option to configure the default for --rollback right? Can you explain the scenario where it is useful? Also note click default_map works too.

**Comment by sbidoul** [comment]
I documented get_odoo_args in https://github.com/acsone/click-odoo/commit/2a3831b188c687c0093785b4099affa8144f73bf. It is marked experimental until we have more feedback on it's usage.

Don't hesitate to open issues for real-world use cases that are not covered by the current API.

Thanks for your input.

**Comment by blaggacao** [comment]
I'm in a bit of an awkward situation right now:
- Given the track record I was foreseeable for me that you would undertake such a big refactoring.
- As I consequence I pushed forward because I needed to progress with the agenda.
- Now I have a situation where I would need to migrate everything back again (as you finally adopted most of my feedback) and I'm not sure if I want to do another tedious cycle on this any time soon.

I think I'll decide a little later what to do and for the time being track upstream development closely, but selectively for my use case. I consider it pretty stable already, so it shouldn't be too much of a moving target.
Next time, maybe this implicit (and unfortunate) misunderstanding can be avoided with a little more verbosity :wink: 

Thanks anyhow, I learned great things in this process either by you pushing or teaching me! I'm very grateful for that! IN the meanwhile, count with my commitment to also improve `click-odoo` 1.x where pertinent.

**Comment by sbidoul** [comment]
Well I told you from the beginning that I did not want backward incompatible changes. And creating an issue to explain and discuss the use case before creating a PR is always a good thing to do.

That said, coming back to this version should be quite a trivial change for you.

If you decide to maintain a fork, up to you of course. I'll ask you to change the name of the project in that case, to avoid confusing people.

**Comment by blaggacao** [comment]
Rest assured, I'm strongly committed to collaboration. On that foundation, I see no major problem going forward.

I don't attribute the misunderstanding to any particular Issue or PR, yet to the overall interaction. That's a hint in the spirit of all honesty and openness and under the assumption it is of any interest.

**Pull request closed without merging**
