### PR TITLE
support launching with ``python -m click_odoo``

### LINKED ISSUE #20: Crash Error use click-odoo
Hi,

I used click-odoo from console in a enviroment python3.6, i have odoo11 installed and it shows:

-----

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env.py", line 8, in <module>
    import odoo
ModuleNotFoundError: No module named 'odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env.py", line 15, in <module>
    import openerp as odoo
ModuleNotFoundError: No module named 'openerp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/bin/click-odoo", line 7, in <module>
    from click_odoo.cli import main
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/__init__.py", line 4, in <module>
    from .env_options import env_options  # noqa
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env_options.py", line 11, in <module>
    from .env import OdooEnvironment, odoo
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env.py", line 20, in <module>
    raise ImportError("No module named odoo nor openerp")
ImportError: No module named odoo nor openerp

----

I have to do some configuration?

### PR DESCRIPTION
**Pull request by sbidoul**
fixes #20

### CODE REVIEW

**Comment by eLBati** [comment]
@sbidoul I still can't make it work when odoo is not installed with pip.
I have a local virtualenv where I installed click-odoo with `pip install git+https://github.com/acsone/click-odoo.git@minusm-sbi` but where odoo is not installed with pip: I launch it with `python3 parts/odoo/odoo-bin -c odoo/odoo.cfg`
And `click-odoo` keeps raising
```
Traceback (most recent call last):
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env.py", line 8, in <module>
    import odoo
ImportError: No module named 'odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env.py", line 15, in <module>
    import openerp as odoo
ImportError: No module named 'openerp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/bin/click-odoo", line 7, in <module>
    from click_odoo.cli import main
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/__init__.py", line 4, in <module>
    from .env_options import env_options  # noqa
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env_options.py", line 11, in <module>
    from .env import OdooEnvironment, odoo
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env.py", line 20, in <module>
    raise ImportError("No module named odoo nor openerp")
ImportError: No module named odoo nor openerp
```

Testing from odoo dir
`parts/odoo$ click-odoo -h`
and
`parts/odoo/odoo$ click-odoo -h`
still raises the error

**Comment by sbidoul** [comment]
@eLBati have you tried `python -m click_odoo` from the Odoo root directory?

**Comment by sbidoul** [comment]
@eLBati yes that's the point of this PR :)

As I tried to explain `click-odoo` is a setuptools console script that uses the pythonpath of the virtualenv. It is normal it does not add the current directory in pythonpath, to be sure it's behaviour is the same wherever you launch it.

When you run `python`, the current directory is added to the pythonpath. Hence the need to run `python -m click_odoo` to have it work when Odoo is not installed nor in pythonpath.

Do you think the updated doc in this PR is clear enough?

**Comment by eLBati** [comment]
I think it is

**Comment by sbidoul** [comment]
Ok, thanks a lot for your tests and feedback.

**Pull request merged**
