### PR TITLE
[REF] 2.0.0

### PR DESCRIPTION
**Pull request by blaggacao**
And yet another refactoring intent:

- Cleaner code. 
- Easier to maintain.
- Leverage click machinery.
- Doesn't repeat click functionality (like flag defaulting)
- Easier to extend.
- KISS (avoide wrap wrap wrap)
- Additional tests.
- Avoid click API masking.
- More stable.

### CODE REVIEW

**Comment by sbidoul** [comment]
I still don't understand what problem you are trying to resolve... so I don't see any compelling reason to do such a big, backward incompatible change.

**Comment by blaggacao** [comment]
I also feel there is a slight inconsistency in your argument:

- Semver major versions declare backwards incompatible changes.
- Therefore and given it's labeled 2.0.0, it's not a question of "if".

I can see however how the question of "when" is much in favour of a time where adoption is only slowly picking up.

**Comment by blaggacao** [comment]
Concrete suggestion to move on:

- Fork master to 1.x branch
- Accept this PR on master (it's feature par and has some extra tests)
- Decide when problems arise if it's better to migrate downstream or fix in 1.x
- Adopt 2.x for new projects.

I don't see what could be against such procedure, given that I offer to forward port fixes and features from 1.x.

**Comment by blaggacao** [comment]
Closing as replaced by #17 (for maintainability reasons on my end) , but let's keep discussing it here.

**Pull request closed without merging**
