### PR TITLE
Add environment_factory to click_odoo.env_options

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
@blaggacao this should enable the use cases you mention in #9, including lazy loading of the environment if you so desire (by returning an Environment proxy that loads on first `__call__`/`__getattr__`)).

**Comment by blaggacao** [comment]
Yeah! I like this way better! :-)
I learned that true lazy evaluation is not something python excels (evaluate `env` only at the first _access_)

I'll later push a WIP attempt to make the config be loaded through that factory (so at the latest possible point in time) via a Config constructor class.

**Comment by sbidoul** [comment]
The goal is that you have a hook to do what you need, so there should be no need to change click-odoo much further in this area.

**Comment by blaggacao** [comment]
Hm the Config delay would be a solution in search of a problem. That was stupid.

However, providing a class could provide better inheritance.

**Comment by sbidoul** [comment]
Inheritance of what. Despite everything we do in Odoo, I'd rather avoid customization by inheritance.

**Comment by blaggacao** [comment]
```python
class OdooConfig(object):
    """ Construct class for odoo command line args """

    def __init__(self, config=None, database=None,
                 log_level=None, logfile=None, **kwargs):
        self.config = config
        self.database = database
        self.log_level = log_level
        self.logfile = logfile
        self.kwargs = kwargs

    def _parse(self):
        odoo_args = []
        if self.config:
            odoo_args.extend(['-c', self.config])
        if self.database:
            odoo_args.extend(['-d', self.database])
        if self.log_level:
            odoo_args.extend(['--log-level', self.log_level])
        if self.logfile:
            odoo_args.extend(['--logfile', self.logfile])
        return odoo_args

    def seed(self):
        """ Seed the odoo config object """
        series = odoo.release.version_info[0]
        # reset db_name in case we come from a previous run
        # where database has been set, in the second run the is no database
        # (mostly for tests)
        odoo.tools.config['db_name'] = None
        # see https://github.com/odoo/odoo/commit/b122217f74
        odoo.tools.config['load_language'] = None
        odoo.tools.config.parse_config(self._parse())
        _fix_logging(series)
        odoo.cli.server.report_configuration()
```

**Comment by blaggacao** [comment]
@sbidoul Would you already merge this? It's a perfect solution for further exploring my use case...

**Comment by blaggacao** [comment]
Thank you! :smile:

**Pull request merged**
